### ISSUE TITLE
Problem with iOS platform

### ISSUE THREAD

**Issue by mfossel** [opentok/opentok-ionic-samples#12]
Hey guys, I am trying to install the latest version in my app.

I am able to add it with cordova but when I prepare my project for iOS I get this problem.

`Installing "cordova-plugin-opentok" for ios
Downloading OpenTok iOS SDK
downloaded
(node:151533) DeprecationWarning: exec: use child_process.execFile instead
expanded
moved OpenTok.framework into /home/ubuntu/workspace/lash-mobile/plugins/cordova-plugin-opentok/src/ios/
Removed extracted dir
Removed downloaded SDK
Error during processing of action! Attempting to revert...

Failed to install 'cordova-plugin-opentok': CordovaError: Uh oh!
Cannot find framework "/home/ubuntu/workspace/lash-mobile/plugins/cordova-plugin-opentok/src/ios/OpenTok.framework" for plugin cordova-plugin-opentok in iOS platform
    at install (/home/ubuntu/workspace/lash-mobile/platforms/ios/cordova/lib/plugman/pluginHandlers.js:109:48)
    at Object.process (/home/ubuntu/workspace/lash-mobile/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/ubuntu/workspace/lash-mobile/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/ubuntu/workspace/lash-mobile/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/home/ubuntu/workspace/lash-mobile/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)

(node:151533) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Uh oh!
Cannot find framework "/home/ubuntu/workspace/lash-mobile/plugins/cordova-plugin-opentok/src/ios/OpenTok.framework" for plugin cordova-plugin-opentok in iOS platform`

Seems as if the download of the iOS SDK is failing. Any ideas on how to get past this? thanks

**Comment by mfossel** [comment]
After a few tries it worked.

**Comment by msach22** [comment]
@mfossel glad to hear that this is working. Out of curiosity, how often did the download fail for you?

**Comment by mfossel** [comment]
It happened 2 or 3 times before it worked and then I made a build and didn't try again. I'll let you know if it happens again, thanks.

**Comment by msach22** [comment]
Thanks, @mfossel !

**Comment by LokeshPatel** [comment]
Hi,
I've same issue, please help for resolve this issue.
Thanks

**Comment by msach22** [comment]
@LokeshPatel can you share your installation process? Is this happening when you clone the `opentok-ionic-samples` repo or when you're adding the plugin to an `ionic` project?

**Comment by LokeshPatel** [comment]
I've used in cordova app, install plugin using cordova plugin add cordova-plugin-opentok.
Using this https://github.com/opentok/cordova-plugin-opentok.
Thanks

**Comment by brunosoune** [comment]
Hello @msach22 ,

I've same issue, any solution?

Thanks

**Comment by msach22** [comment]
@LokeshPatel and @brunosoune are you both seeing the same trace? Could you please provide the following:
 - Node.js version
 - Ionic version
 - OS

Please also provide anything else that you believe is useful so I can replicate this on my end.

**Comment by brunosoune** [comment]
I was able to solve this problem as follows:

I manually downloaded the OpenTok IOS SDK from [this link](https://tokbox.com/downloads/opentok-ios-sdk-2.14.0), extracted and copied the OpenTok.framework folder into ../plugins/cordova-plugin-opentok/src/ios/.
I ran the _cordova plugin-add-cordova-plugin-opentok_ command again and it worked.

Thanks and I hope helpfull.

**Comment by msach22** [comment]
@brunosoune First off, my apologies for missing the issue. Secondly, I'm glad that it worked for you. It seems that there is an issue downloading the iOS SDK when phonegap is involved. I'll explore an alternative iOS solution (possibly via CocoaPods) and keep you updated!

**Comment by brunosoune** [comment]
Thanks @msach22 !

**Comment by mmubasher** [comment]
Any solutions found for this issue? I am getting the same error in following environment
```
Node      10.13.0
Cordova   8.1.2 
Ionic CLI  4.3.1
npm        6.4.1
Phonegap - Not Installed
```

**Comment by msach22** [comment]
@mmubasher Do you have the iOS and Android platforms installed? Are you unable to download the SDK when you do `cordova plugin add cordova-plugin-opentok` ?

**Comment by msach22** [comment]
@mmubasher I'm happy to hear that it's working - Thanks for sharing!

**Comment by KasunGamage** [comment]
try to remove the platform and add it again before you do the build.hope this help.

**Comment by henritoivar** [comment]
For some SDK versions the extracted directory name is not the same as the tar file name. Thus the `mv` command fails in `downloadiOSSDK.js`
