### ISSUE TITLE
ReferenceError: OT is not defined

### ISSUE THREAD

**Issue by bivav** [opentok/opentok-ionic-samples#17]
Hi,
I followed all the steps you mentioned and the app built correctly. All the packages installation also completed successfully without giving error.
But once it launches localhost:8100
It displays this error:

`ReferenceError: OT is not defined
    at HomePage.webpackJsonp.194.HomePage.startCall (http://localhost:8100/build/main.js:64:24)
    at Object.eval [as handleEvent] (ng:///AppModule/HomePage.ngfactory.js:33:31)
    at handleEvent (http://localhost:8100/build/vendor.js:13607:172)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15092:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:14679:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:10056:25)
    at http://localhost:8100/build/vendor.js:10670:38
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:36346:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4970:33)`

I don't know if this is error in app or network side.

**Comment by Jasonseah** [comment]
@msach22 I had run into the same issue, the problem happened on the web. After inserted the apiKey and all stuff it still showing OT is not define

**Comment by bivav** [comment]
Hi @msach22 ,
Thanks for you message. Sorry, that was error in web browser, I didn't realize it that time.
The actual error I got now after installing in android app is this

`06-11 12:15:07.496 10085-10085/io.ionic.starter E/OTPlugin: session exception: Unable to connect: an invalid session ID was provided.`

The application runs and when I press "Start OpenTok Call" that is the error I get in Logcat.
I think this is because my app couldn't connect to the local server? is it? How can I solve this?

**Comment by Jasonseah** [comment]
Hey @bivav,
Please make sure you have your sessionId, apiKey and token are not empty.

**Comment by bivav** [comment]
Hi @Jasonseah,
Thanks for you reply!
Indeed that's the problem it seems. I am trying to find where I need to keep my credentials. Could you tell me which file should consist that? 
Thank you!

**Comment by bivav** [comment]
@Jasonseah @msach22 
I found the file and now it works! 
Thanks for your help!

**Comment by Jasonseah** [comment]
Hey @bivav,
navigate to this file `/src/pages/home/home.ts` then you will see 3 empty variables just put it accordingly then it should be working.

**Comment by msach22** [comment]
@Jasonseah Thanks for helping out! 

I'm glad it's working for @bivav!

**Comment by david95thinkcode** [comment]
Hey guys, 
I'm facing the same problem since the morning and I've tried all solutions  above but nothing is working. 

Can I get a full working example repo ?

**Comment by msach22** [comment]
@david95thinkcode Is `OT` coming back as undefined for iOS, Android, or web?

**Comment by ayubUOL** [comment]
@msach22 I'm using my credentials but OT is undefined in web and also facing problems in building Android APK. Need your help Sir

**Comment by ayubUOL** [comment]
@msach22 
Trying to build APK file for it but facing error in opentok plugin gradle file.
`dependencies { implementation fileTree(dir: 'libs', include: ['*.jar']) implementation 'com.opentok.android:opentok-android-sdk:2.15.1' }`

**Comment by msach22** [comment]
Can you confirm that you've added the opentok.js file to your index.html?

Are you building the APK from Android studio?

**Comment by ayubUOL** [comment]
@msach22 Yes i've added the opentok.js file in index.html
And building APK using IONIC CLI

**Comment by msach22** [comment]
@ayubUOL Hmm, I just ran the Basic Video Chat project with the latest version of the plugin and was able to build an APK successfully through the CLI. Could you please try with this sample application and see if it works for you?

**Comment by ayubUOL** [comment]
@msach22 I tried with your sample application and faced problem. Can you please share your Android Specs and SDK version ?

**Comment by ayubUOL** [comment]
@msach22 Mine is **Android 6.3 and SDK tools is 26.1.1**

**Comment by StevenMitrais** [comment]
> @msach22
> **Could not find method implementation() for arguments [directory 'libs'] on object of type org .gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.**
> 
> Trying to build APK file for it but facing error in opentok plugin gradle file.
> `dependencies { implementation fileTree(dir: 'libs', include: ['*.jar']) implementation 'com.opentok.android:opentok-android-sdk:2.15.1' }`

This one just change from **implementation** to **compile**
...\Basic-Video-Chat\platforms\android\cordova-plugin-opentok\starter-build-extras.gradle
