### ISSUE TITLE
Publisher and subscriber video containers issue

### ISSUE THREAD

**Issue by asukita** [opentok/opentok-ionic-samples#20]
Hello!

I'm creating an class room ionic application, our front will be in web, ios and android.
In web, the video containers of subscriber and publisher works fine, but when I run in android or ios the container overlay everything and we can't make some actions inside the class room like close modals or touch some buttons.

And appears that they are floating outside the divs that have to contain it.

My question is, can we hide or move this containers programatically? I attached some screenshots, tell me if you need more info.

![captura de pantalla 2018-08-15 a la s 12 54 05](https://user-images.githubusercontent.com/4505117/44165490-827f9680-a08e-11e8-8ee5-f7a7fe177420.png)
![captura de pantalla 2018-08-15 a la s 13 00 11](https://user-images.githubusercontent.com/4505117/44165492-827f9680-a08e-11e8-8115-a183af5415db.png)

Thanks for the support!

**Comment by mark-veenstra** [comment]
Can you share your HTML and CSS?

**Comment by asukita** [comment]
Hi! Of course, the html is:

<ion-content>
	<div class="popup-menu">
		<div class="popup-menu-overlay" [ngClass]="{'in': openMenu}" (click)="togglePopupMenu()"></div>
		<div class="popup-menu-toggle gradientbg-secondary" (click)="togglePopupMenu()" [ngClass]="{'out': openMenu}"></div>
		<div class="popup-menu-panel" [ngClass]="{'in': openMenu}">
			<div class="popup-menu-item" (click)="mobileActiveTabSelect(3)">
				...
			</div>
		</div>
	</div>	
	<ion-grid class="patternbg-class" *ngIf="!classStarted" style="height: 100vh; padding: 250px auto">
		<ion-row padding-vertical>
			<ion-col text-center>
				...
			</ion-col>
		</ion-row>
	<ion-grid>
	<div id="videocall-images">
			<div id="subscriber"></div>
			<div id="publisher"></div>
	</div>
</ion-content>

I remove all the CSS for publisher and subscriber divs and now it fits with their respective divs containers, but they still on top of everything, I attached another image.
![photo from pamela vargas](https://user-images.githubusercontent.com/4505117/44236604-35292500-a173-11e8-8aa1-0b6798a976d8.jpg)

I appreciate all the support :)

**Comment by asukita** [comment]
It works, thanks for the support :)

**Comment by alexisjcr07** [comment]
Hello, I have the same error, but in my case I am trying to show another view on the video.

my code:
.ts

none(){
this.cc = 'none';
this.style = 'none';
}
block(){
this.cc = 'block';
this.style = 'block';
}

    streamCreated: (event) => {

    let subscriberProperties = {width:"100%",height:"91% !important"};

    if(event.stream.videoType === 'screen') {
    this.session.subscribe(event.stream, 'screen-preview', subscriberProperties);
    this.none();
 }else 
   {
    this.session.subscribe(event.stream, 'subscriber', subOptions);
    this.block();
    OT.updateViews();
    
   }
  },

.html
.css
#subscriber {
width: 100% !important;
top: 0;
height: 91% !important;
overflow: hidden;
position: fixed;
margin: 0px;
background: #0c0c0c;
left: 0px;

}

.none {
width: 100% !important;
top: 0;
height: 91% !important;
overflow: hidden;
position: relative;
margin: 0px !important;
left: 0px;
display: none !important;

}

.block {
width: 100% !important;
top: 0;
height: 91% !important;
overflow: hidden;
position: relative;
margin: 0px !important;
left: 0px;
display: block !important;

}

#publisher {
width: 30% !important;
height: 18% !important;
overflow: hidden;
position: fixed;
margin: 0px !important;
right: 14px;
bottom: 80px;
left: auto;
z-index: 40;
}

#screen-preview {
width: 100% !important;
top: 0;
height: 91% !important;
overflow: hidden;
position: fixed;
margin: 0px !important;
background: transparent !important;
z-index: 999;
left: 0px;
}
