### ISSUE TITLE
OT.updateViews is not a function error

### ISSUE THREAD

**Issue by Shtibel** [opentok/opentok-ionic-samples#22]
I just build and run the sample app on android
When users start to join I get this error:

OT.updateViews is not a function error

**Comment by Shtibel** [comment]
Hi @ayubUOL
your request is not relevant to this issue.
Please open a new issue and I will try to help you.

**Comment by ayubUOL** [comment]
@Shtibel  I know and I opened new issue but no one is replying me there .
Below link is the issue link I've opened please check 
https://github.com/opentok/opentok-ionic-samples/issues/23

Thank you

**Comment by msach22** [comment]
@Shtibel `OT.updateViews` is a function that's only used for the mobile apps - it's not a part of the JS SDK. I've filed an issue in the plugin repo https://github.com/opentok/cordova-plugin-opentok/issues/136

**Comment by msach22** [comment]
Closing this issue because it's not an issue with the plugin - the function is only valid for mobile apps.
