### ISSUE TITLE
Detect the stream of the person who started the conference

### ISSUE THREAD

**Issue by Shtibel** [opentok/opentok-ionic-samples#24]
Hi there,

What I want to do is: 
An organizer starts a video conference session 
I generate on my server a new session id and generate a new token for the organizer with role of 'Moderator' 
And when other users join this session I generate for them tokens with role of 'Publisher'

All the users must see the organizer video stream in full screen and all the other participants in small videos streams 
So organizer see himself in full screen and other users in small videos 
And other participants see the organizer in full screen and themselves and other participants in small videos 
you can see in the attached image what I want to achieve.

![conf](https://user-images.githubusercontent.com/24429607/49882076-7dfa9d00-fe38-11e8-9657-751d8d2e7f00.png)

Now what happens is that when a new user joins the conference he see himself in the full screen instead of the organizer. 
How can I make this happen?

This is my code now:

   
      this.session = OT.initSession(this.apiKey, this.sessionId);
      this.session.on({
        streamCreated: (event) => {
          this.session.subscribe(event.stream, 'subscriber',{
            insertMode: 'append',
            width: '90px',
            height: '90px'
          });
          OT.updateViews();
          this.showSpinner = false;
        },
        streamDestroyed: (event) => {
          console.log(`Stream ${event.stream.name} ended because ${event.reason}`);
          OT.updateViews();        
        }
      });
      
      this.session.connect(this.token, () => {
        console.log('publish: ',this.session.capabilities.publish);

        this.publisher = OT.initPublisher('publisher', {
          width: '100%',
          height: '100%'
        });
        this.session.publish(this.publisher);
        this.showSpinner = false;
      });

**Comment by msach22** [comment]
@Shtibel You can update the style for the publisher using CSS and make them the focus image on the screen. Please make sure to call `OT.updateViews()` after you make the CSS changes.

**Comment by Shtibel** [comment]
Yes I figured it out.
Thank you @msach22

**Comment by msach22** [comment]
No problem, I'm going to go ahead and close this issue
