### ISSUE TITLE
ionic hybrid app ios published stream not showing up in the playground

### ISSUE THREAD

**Issue by hash-bud** [opentok/opentok-ionic-samples#30]
Iphone 6 after clicking "Start Call"
![iphone6_after_start_call](https://user-images.githubusercontent.com/47208828/52264573-fde44580-2957-11e9-9dc9-34926c72d7e7.jpg)

Playground View
<img width="504" alt="iphone_video stream_not_showing" src="https://user-images.githubusercontent.com/47208828/52261706-36802100-2950-11e9-84c6-0f6a47a9c4d0.png">

After clicking start call in the ios app(Followed the instructions in the readme), opened the playground.
App shows 2 streams( one from ios and other from the laptop).
But in the playground, Stream from the iphone is not shown.
Didn't do any code  change other that apiKey, sessionId and token update.
Mic and Camera permissions are also added to the info.plist.

Why is this happening? 
When I use the older plugin i don't get this issue.( https://github.com/msach22/cordova-plugin-opentok)
Seems like a bug in new plugin (https://github.com/opentok/cordova-plugin-opentok)

ionic 3, cordova-ios 4.5.5, iphone 6, ios 12.1.2, Cordova Plugin for OpenTok 3.4.4

**Comment by voxiel** [comment]
I have the same problem, seems like iOS can't publish a stream, just subscribe to a stream in the session. The weird part is that in the app the camera takes the video. 

I'll try with the older plugin, maybe it helps

**Comment by totiherms** [comment]
same issue. I've tried with cordova-plugin-opentok versions 3.4.3 to 3.3.0 with no success
