### ISSUE TITLE
cordova-plugin-opentok version 3.4.3 does not work with the current sample application

### ISSUE THREAD

**Issue by Shtibel** [opentok/opentok-ionic-samples#31]
We updated to cordova-plugin-opentok 3.4.3 and the sample stopped working.
We downgraded to 3.4.2 it works.

Please check it.
Thank you!

**Comment by msach22** [comment]
@Shtibel Yes, there was a bug with the error handler that was fixed with 3.4.3. We should update the sample application to leverage the bug fix with the error handler.

**Comment by msach22** [comment]
Closing this issue because I've updated the sample application with the best practices
