### ISSUE TITLE
Incoming real call after session ended - phone is not ringing

### ISSUE THREAD

**Issue by Shtibel** [opentok/opentok-ionic-samples#35]
# Bug Report

**Testing platform**
> Android, Ionic, cordova

**Current behavior**
> After an openTalk session has ended, If I get a real incoming call the call is silent, What I mean is that the phone is not ringing, it is like a waiting call. Only if I close the application I get a ringing sound for incoming calls.

**Steps to reproduce**
> Create a session > join a session with other users > receive a regular phone call > you will see that you will receive the call as a waiting call with no ringing sound. > close the session / exist the session and leave the application open > receive a regular phone call > you will see that you still receive the call as a waiting call. > close the application > receive a regular phone call > you will see that you will receive the call with a ringing sound. 

**Example Project**
> https://github.com/opentok/opentok-ionic-samples

**What is the current *bug* behavior?**
> Even after closing/existing a session when I receive a regular phone call I don't get it with a ringing sound but as a waiting call

**What is the expected *correct* behavior?**
> After closing/existing a session when a regular call is received it needs to be as a normal call with ringing sound and not as a waiting call

**Relevant logs and/or screenshots**
> I uploaded a screen cast video that shows the problem, see this video: https://www.youtube.com/watch?v=kDU1EQlg60k

**Comment by msach22** [comment]
Closing this issue because this is a duplicate: https://github.com/opentok/cordova-plugin-opentok/issues/162
