### ISSUE TITLE
IOS - Incompatible Browser

### ISSUE THREAD

**Issue by yaganalldoctors** [opentok/opentok-ionic-samples#39]
The following error happens when I start the session on the Iphone with IOS 12. Unable to connect with Subscriber and start Publisher.

```
Warning - Incompatible Browser

The video component of this application is not supported on your mobile device's browser at this time.
```

**Comment by apatelVse** [comment]
I have same issue on IOS device . did find answer or solved this issue?

**Comment by Bassline528** [comment]
did you solved this issue?
