### ISSUE TITLE
OT.publisher access denied: End-user denied permission to hardware devices

### ISSUE THREAD

**Issue by neerajrpa** [opentok/opentok-ionic-samples#50]
I have integrated Opentok IONIC sample code successfully but when I run app apk on my mobile it is showing me error "OT.publisher access denied: End-user denied permission to hardware devices (getUserMedia error: NotAllowedError) Note: Chrome requires HTTPS for camera and microphone access".

If anyone has faced such an issue, please tell me the solution.

Thanks

**Comment by brijesh-baser** [comment]
Have you find any solution for above issue. We are also facing the same problem.

**Comment by hamdiwanis** [comment]
you have to get the user permission for camera and audio recording first

**Comment by brijesh-baser** [comment]
@hamdiwanis  Thanks for the reply. I am not getting camera and audio recording permission popup.
How to give the permission for camera and audio recording. Any settings?

**Comment by hamdiwanis** [comment]
you would use cordova-plugin-android-permissions to get it see here
https://ionicframework.com/docs/native/android-permissions

**Comment by brijesh-baser** [comment]
@hamdiwanis  Thanks for solution, now its working.
