### ISSUE TITLE
Getting another copy of divisions, when subscribe or publisher connected

### ISSUE THREAD

**Issue by rsgone** [opentok/opentok-ionic-samples#6]
Hi,

I am trying to use this same example in one of my apps. When I tried to execute this example I am getting 2 layers for each division, out of those 2 layers of the same DIV, the bottom layer is in our control. which is a blank black box. And on top layer video is streaming, which we can not control(resize, scroll, apply css etc..)

And when I try to scroll HTML page or apply any CSS, JS operations to the div which I created. It is affecting to bottom layer DIVs. 

![image002](https://user-images.githubusercontent.com/12427522/34534775-7be06bc8-f0e5-11e7-8a70-27ac3764fd66.png)

![skype_picture 2](https://user-images.githubusercontent.com/12427522/34534986-69319cc6-f0e6-11e7-92d5-65502364c6a9.jpeg)

After some googling, I realized that, OT.updateViews() or TB.updateViews() function will solve this issue, but no luck. :(

Here is my code:

    startCall() {
    this.session = OT.initSession(this.apiKey, this.sessionId);
    this.session.on({
      streamCreated: (event) => {
        var pubOptions = { publishAudio: true, publishVideo: true };
        this.session.subscribe(event.stream, 'subscriber', pubOptions);
        OT.updateViews();
      },
      streamDestroyed: (event) => {
        console.log(`Stream ${event.stream.name} ended because ${event.reason}`);
        OT.updateViews();
      }
    });

    this.session.connect(this.token, () => {
      this.publisher = OT.initPublisher('publisher');
      this.session.publish(this.publisher);
      OT.updateViews();
    });
  }

Thanks for the help in advance.

**Comment by msach22** [comment]
@rsgone Could you provide me with any styles that you're applying to the `publisher` and `subscriber` divs so I can try to reproduce this?

As for the multiple div containers, there is a webview div which is a part of the DOM and the other is a native video component which should be superimposed on the webview div.

**Comment by rsgone** [comment]
Hi @msach22, We have not applied any styles to the publisher and subscriber, yet as we were trying to resolve the superimposing issue.however, we can see some styles in inspect window, which is generated dynamically by opentok.js file, 

Here is our HTML code:    
    <div style="text-align:center">
        <button (click)="startCall()">Start OpenTok Call</button>
    </div>
    <div id="subscriber"></div>
    <div id="publisher"></div> 

a) webview div which is a part of the DOM -->  This I am able to control(I can play with all options of  CSS) this DIV.
b) native video component which should be superimposed on the webview div --> I am not able to control the native components, and therefore not able to superimpose it on webview div.(Since I could not capture the video component, I could not apply CSS to this video streaming div)

Could you please help us understand, how to control the native component and superimpose it?

Thank you

**Comment by msach22** [comment]
@rsgone I replied to George a little earlier, but wanted to cc the response here: 
When you call OT.updateViews(), it updates the sizing and positioning of these overlayed views to match the elements inside the WebView. As of now, scrolling of the native video elements only work on iOS, but for Android devices, you may be able to listen for a scroll event in the JS layer and call OT.updateViews() so the native element can be moved.
Something like the following may work:

```
window.addEventListener('scroll', function() {
   OT.updateViews();
}, );
```
Please keep in mind that I have not tested this. I'll be syncing with George via email and closing out this issue, but I've created an issue regarding this in the Cordova OpenTok Plugin repo where the change should be implemented: https://github.com/opentok/cordova-plugin-opentok/issues/10
