### ISSUE TITLE
ionic android  OT_HARDWARE_UNAVAILABLE

### ISSUE THREAD

**Issue by gchokeen** [opentok/opentok-ionic-samples#73]
Hi,

Video call is not working, I'm getting following error when I run in the real android device. It was working on chrome browser.

Error
> OpenTok:Publisher:error onStreamAvailableError OT_HARDWARE_UNAVAILABLE: The selected voice or video devices are unavailable. Verify that the chosen devices are not in use by another application. (getUserMedia error: NotReadableError)

Implemented code

```

  startCall(item) {

    this.sessionId = item.meeting_id;
    this.token = item.meeting_token;

    console.log(item);


    var connectionCount = 0;



    if(this.sessionId){

      var publisherOptions = {
        insertMode: 'append',
        width: '100%',
        height: '50%',
        name:this.user.name,
        showControls:true,
        publishAudio:true, 
        publishVideo:true
      };

      this.session = OT.initSession(env.OPENTOK.API_KEY, this.sessionId);
      this.publisher = OT.initPublisher('publisher',publisherOptions);
  
      this.session.on({
        streamCreated: (event: any) => {
          this.session.subscribe(event.stream, 'subscriber');
          //OT.updateViews();
        },
        streamDestroyed: (event: any) => {
          console.log(`Stream ${event.stream.name} ended because ${event.reason}`);
         // OT.updateViews();        
        },
        sessionConnected: (event: any) => {
          this.session.publish(this.publisher);
               
        },
        connectionCreated: (event: any) => {
          connectionCount++;
          console.log(event);
        },
        connectionDestroyed: (event: any) => {
          connectionCount--;
          console.log(event);

        },

      });
  
      this.session.connect(this.token, (error: any) => {
        if (error) {
          console.log(`There was an error connecting to the session ${error}`);
        }



      });

    }

  }

```

ionic info

> 
> Ionic:
> 
>    Ionic CLI                     : 6.10.1 (/Users/user/.nvm/versions/node/v10.18.1/lib/node_modules/@ionic/cli)
>    Ionic Framework               : @ionic/angular 4.11.10
>    @angular-devkit/build-angular : 0.13.10
>    @angular-devkit/schematics    : 7.3.10
>    @angular/cli                  : 7.3.10
>    @ionic/angular-toolkit        : 1.5.1
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : android 8.1.0
>    Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 18 other plugins)
> 
> Utility:
> 
>    cordova-res : 0.15.1
>    native-run  : 1.0.0
> 
> System:
> 
>    NodeJS : v10.18.1 (/Users/user/.nvm/versions/node/v10.18.1/bin/node)
>    npm    : 6.14.5
>    OS     : macOS High Sierra
>

**Comment by tainefreitas** [comment]
Me too! Do you find a workaround?

**Comment by gchokeen** [comment]
It was because of camera and microphone permission! I used https://ionicframework.com/docs/v3/native/diagnostic/ plugin to gain user permissions for camera and micro phone before the call button code.

**Comment by apatelVse** [comment]
I added diagnostic plugin for IOS and then trying to OT.initPublisher but still getting error 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43278326/94595281-9e3b5c00-0258-11eb-8edf-8f811268a2a7.png">

and when I was checking getDevices throws bellow error <img width="406" alt="image" src="https://user-images.githubusercontent.com/43278326/94595146-69c7a000-0258-11eb-8ebc-ebbf69b7d6e0.png">

I also tried after adding permission for camera and microphone using daignostic permission , OT.getUserMedia return rejected callback.

Please can help here?

**Comment by gchokeen** [comment]
@apatelVse I faced the same think and I noticed still mic & camera was not enabled, So once I manually enabled it from settings it worked ok. I still don't have correct solutions to make it work on the fly!

**Comment by apatelVse** [comment]
Thanks for reply.
I checked with n settings and its enabled. But still i am getting this error
